# Generated by Django 5.2.9 on 2026-01-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_end_time_event_event_date_event_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('error_type', models.CharField(choices=[('400', 'Bad Request'), ('401', 'Unauthorized'), ('403', 'Forbidden'), ('404', 'Not Found'), ('405', 'Method Not Allowed'), ('408', 'Request Timeout'), ('429', 'Too Many Requests'), ('500', 'Internal Server Error'), ('502', 'Bad Gateway'), ('503', 'Service Unavailable'), ('504', 'Gateway Timeout'), ('Exception', 'Exception')], max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_string', models.TextField(blank=True, null=True)),
                ('client_ip', models.CharField(max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_errorl_timesta_f18e39_idx'), models.Index(fields=['status_code'], name='core_errorl_status__785459_idx'), models.Index(fields=['path'], name='core_errorl_path_695f50_idx')],
            },
        ),
    ]
