# Generated by Django 5.2.9 on 2026-01-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_duration_event_venue_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='The participant who created this team', on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='core.participant')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this registration belongs to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('joined', 'Joined'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='core.participant')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['event', 'created_at'], name='core_team_event_i_6528eb_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_by'], name='core_team_created_3f854e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'event')},
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['team', 'status'], name='core_teamme_team_id_df050a_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['participant', 'status'], name='core_teamme_partici_e4646d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'participant')},
        ),
    ]
