# Generated by Django 5.2.9 on 2026-01-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed password for team login', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='department',
            field=models.CharField(choices=[('AIDS', 'AI & DS'), ('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=10),
        ),
    ]
