# Generated by Django 5.2.9 on 2026-01-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_password_alter_participant_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='pending_members',
            field=models.TextField(blank=True, help_text='JSON list of pending member register numbers not yet registered', null=True),
        ),
    ]
