# Generated by Django 5.2.9 on 2026-01-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_team_pending_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Whether this participant is a team lead'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='core.team'),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_members',
            field=models.TextField(blank=True, help_text='JSON data of team members', null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, help_text='Team name if participant is team lead', max_length=100, null=True),
        ),
    ]
