# Generated by Django 5.2.9 on 2026-01-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_participant_is_team_lead_participant_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_password',
            field=models.CharField(blank=True, help_text='Team password (hashed) for team login', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='team_password',
            field=models.CharField(blank=True, help_text='Team password (hashed) for team login verification', max_length=255, null=True),
        ),
    ]
