# Generated by Django 5.2.9 on 2026-01-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_participant_team_password_registration_team_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='register_number',
            field=models.CharField(max_length=20),
        ),
    ]
