# Generated by Django 5.2.9 on 2026-01-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_participant_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='register_number',
            field=models.CharField(blank=True, help_text='Unique registration number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='register_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
