# Generated by Django 5.2.9 on 2026-01-25 19:15

import django.db.models.deletion
from django.db import migrations, models


def clear_invalid_team_references(apps, schema_editor):
    """Clear Team.created_by references that point to non-existent Participant records"""
    Team = apps.get_model('core', 'Team')
    Participant = apps.get_model('core', 'Participant')
    Registration = apps.get_model('core', 'Registration')
    TeamMember = apps.get_model('core', 'TeamMember')
    
    # Get all teams with created_by references
    teams_with_creator = Team.objects.exclude(created_by__isnull=True)
    
    # For each team, check if creator is a valid Participant
    for team in teams_with_creator:
        try:
            # Check if created_by_id exists in Participant table
            Participant.objects.get(id=team.created_by_id)
        except Participant.DoesNotExist:
            # Creator doesn't exist, clear the reference
            team.created_by = None
            team.save()

def reverse_clear_references(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registration_register_number_and_more'),
    ]

    operations = [
        # Clear invalid references before removing the Participant model
        migrations.RunPython(clear_invalid_team_references, reverse_clear_references),
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        # Add new fields to Registration FIRST
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(choices=[('AIDS', 'AI & DS'), ('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication'), ('EEE', 'Electrical & Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil'), ('OTHER', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_team_lead',
            field=models.BooleanField(default=False, help_text='Whether this participant is a team lead'),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True),
        ),
        # Add registration field to TeamMember BEFORE updating unique_together
        migrations.AddField(
            model_name='teammember',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='core.registration'),
        ),
        # Now update field types and constraints
        migrations.AlterField(
            model_name='team',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The registration that created this team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to='core.registration'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='register_number',
            field=models.CharField(help_text='Unique registration number', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team this registration belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='core.team'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_members',
            field=models.TextField(blank=True, help_text='JSON data of team members', null=True),
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-registered_at']},
        ),
        migrations.RemoveIndex(
            model_name='teammember',
            name='core_teamme_partici_e4646d_idx',
        ),
        # Now update unique constraints
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('register_number', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'registration')},
        ),
        # Add index for registration
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['registration', 'status'], name='core_teamme_registr_1f4290_idx'),
        ),
        # Remove old fields
        migrations.RemoveField(
            model_name='registration',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='participant',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
