# Generated by Django 5.2.9 on 2026-01-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_participant_events_remove_participant_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='team_members',
            field=models.IntegerField(default=0, help_text='Count of team members (0 if not team lead)'),
        ),
    ]
