# Generated by Django 5.2.9 on 2026-01-26 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_registration_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Training question that users might ask')),
                ('answer', models.TextField(help_text='Chatbot response to this question')),
                ('intent', models.CharField(blank=True, help_text='Intent category (e.g., registration_guide, team_guide)', max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for this Q&A pair', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this training pair')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_training_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intent'], name='core_chatbo_intent_bea696_idx'), models.Index(fields=['is_active'], name='core_chatbo_is_acti_3f4e06_idx'), models.Index(fields=['-created_at'], name='core_chatbo_created_09ba78_idx')],
            },
        ),
    ]
